on:
  pull_request:
    branches:
      - 'main'
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 
          
      - name: Install scrapy
        run: pip3 --install Scrapy
