on:
  push:
    branches:
      - main
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Set up virtual environment
        run: python3 -m venv scrapy-env && source scrapy-env/bin/activate
      - name: Install Scrapy
      - run: pip install scrapy
      - name: Run Spider
        env:
          MAIL_FROM: ${{secrets.MAIL_FROM}}
          MAIL_PWD: ${{secrets.MAIL_PWD}}
          MAIL_TO: ${{secrets.MAIL_TO}}
        run: scrapy crawl houses -O houses.json
